---

- name: restart kafka service
  service:
    name: kafka
    state: restarted

- name: restart kafka systemd
  systemd:
    name: kafka
    state: restarted
    daemon_reload: yes
    
    
- name: restart zookeeper service
  service:
    name: zookeeper
    state: restarted

- name: restart zookeeper systemd
  systemd:
    name: zookeeper
    state: restarted
    daemon_reload: yes
